
###
POST http://localhost:8080/api/proyecto/actaReunion/crearLineaActaReunion HTTP/1.1
Content-Type: application/json


{
  "idActaReunion": 29,
  "nombreReunion": "Reunión de Planificación",
  "fechaReunion": "2023-11-01",
  "horaReunion": "10:00 AM",
  "nombreConvocante": "Juan Pérez",
  "motivo": "Discutir los detalles del proyecto",
  "temas": [
    {
      "descripcion": "Tema 1: Planificación del proyecto 2",
      "acuerdos": [
        {
          "descripcion": "Acuerdo 1: Definir los plazos del proyecto",
          "fechaObjetivo": "2023-11-10",
          "responsables": [
            {
              "idUsuarioXRolXProyecto": 2
            },
            {
              "idUsuarioXRolXProyecto": 4
            }
          ]
        }
      ]
    }
  ],
  "participantes": [
    {
      "idUsuarioXRolXProyecto": 2,
      "asistio": true
    }
  ],
  "comentarios": [
    {
      "descripcion": "Comentario 1: La reunión fue productiva"
    }
  ]
}
###
GET http://localhost:8080/api/proyecto/actaReunion/listarLineaActaReunionXIdLineaActaReunion/152 HTTP/1.1
Content-Type: application/json

{
  "idActaReunion": 29,
  "nombreReunion": "Reunión de Planificación",
  "fechaReunion": "2023-11-01",
  "horaReunion": "10:00 AM",
  "nombreConvocante": "Juan Pérez",
  "motivo": "Discutir los detalles del proyecto",
  "temas": [
    {
      "descripcion": "Tema 1: Planificación del proyecto 2",
      "acuerdos": [
        {
          "descripcion": "Acuerdo 1: Definir los plazos del proyecto",
          "fechaObjetivo": "2023-11-10",
          "responsables": [
            {
              "idUsuarioXRolXProyecto": 2
            },
            {
              "idUsuarioXRolXProyecto": 4
            }
          ]
        }
      ]
    }
  ],
  "participantes": [
    {
      "idUsuarioXRolXProyecto": 2,
      "asistio": true
    }
  ],
  "comentarios": [
    {
      "descripcion": "Comentario 1: La reunión fue productiva"
    }
  ]
}
###
GET http://localhost:8080/api/proyecto/actaReunion/listarLineaActaReunionXIdActaReunion/5 HTTP/1.1
Content-Type: application/json



###
PUT http://localhost:8080/api/proyecto/actaReunion/modificarLineaActaReunion HTTP/1.1
Content-Type: application/json

{
  "idLineaActaReunion": 41,
  "nombreReunion": "Reunión de Planificación",
  "fechaReunion": "2023-11-01",
  "horaReunion": "10:00 AM",
  "nombreConvocante": "Juan Pérez",
  "motivo": "Discutir los detalles del proyecto",
  "temas": [
    {
      "idTemaReunion": 17,
      "descripcion": "Tema 1: Planificación del proyecto 2",
      "acuerdos": [
        {
          "idAcuerdo": 17,
          "descripcion": "Acuerdo 2: Definir los plazos del proyecto",
          "fechaObjetivo": "2023-09-10",
          "responsables": [
            {
              "idResponsableAcuerdo": 32,
              "idUsuarioXRolXProyecto": 2
            },
            {
                "idResponsableAcuerdo": 33,
              "idUsuarioXRolXProyecto": 4
            }
          ]
        }
      ]
    }
  ],
  "participantes": [
    {
      "idParticipanteXReunion": 63,
      "idUsuarioXRolXProyecto": 10,
      "asistio": true
    }
  ],
  "comentarios": [
    {
      "idComentarioReunion": 14,
      "descripcion": "Comentario 1: La reunión fue actualizada"
    }
  ]
}


###
DELETE http://localhost:8080/api/proyecto/actaReunion/eliminarLineaActaReunionXIdLineaActaReunion HTTP/1.1
Content-Type: application/json

{
  "idLineaActaReunion": 96
}