
#### EPICAS
###
GET http://localhost:8080/api/proyecto/backlog/listarEpicas/73 HTTP/1.1
Content-Type: application/json

#### SPRINTS ####

###
POST http://localhost:8080/api/proyecto/backlog/insertarSprint HTTP/1.1
Content-Type: application/json

{
    "idProductBacklog": 78,
    "nombre": "Sprint prueba con sprint null unu",
    "descripcion": "Sprint 1",
    "fechaInicio": "2021-05-01",
    "fechaFin": "2021-05-15",
    "estado": 1
}
###
GET http://localhost:8080/api/proyecto/backlog/listarSprintsXIdBacklog/73 HTTP/1.1
Content-Type: application/json
###
DELETE http://localhost:8080/api/proyecto/backlog/eliminarSprint HTTP/1.1
content-type: application/json

{
    "idSprint": 2,
    "tareas": []
}

#### TAREAS ####
###

GET http://localhost:8080/api/proyecto/cronograma/listarTareasXidProyecto/156 HTTP/1.1
Content-Type:  application/json

###
PUT http://localhost:8080/api/proyecto/cronograma/actualizarIdSprintXTarea HTTP/1.1
Content-Type: application/json

{
    "idTarea": 208,
    "idSprint": 3
}

###
GET http://localhost:8080/api/proyecto/backlog/listarSprintsXIdBacklogcronograma/78/56 HTTP/1.1
Content-Type: application/json


###
GET http://localhost:8080/api/proyecto/backlog/listarSprintsXIdBacklogcronograma/80/58 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8080/api/proyecto/backlog/actualizarEstadoSprint HTTP/1.1
Content-Type: application/json

{
    "idSprint": 8,
    "estado": 2
}