###

POST http://localhost:8080/api/proyecto/cronograma/insertarTarea HTTP/1.1
Content-Type:  application/json

{
    "idCronograma": 1,
    "idTareaEstado": 2,
    "idSubGrupo": 3,
    "idPadre": 4,
    "idTareaAnterior": 5,
    "idSprint": 3,
    "sumillaTarea": "Sumilla de la tarea",
    "descripcion": "Descripción detallada de la tarea",
    "fechaInicio": "2023-10-20",
    "fechaFin": "2023-10-25",
    "cantSubtareas": 2,
    "cantPosteriores": 1,
    "horasPlaneadas": 40,
    "usuarios": [
        {
            "idUsuario": 77
        },
        {
            "idUsuario": 78
        }
    ],
    "subTareas": [
        {
            "body": {
                "idCronograma": 1,
                "idTareaEstado": 2,
                "idSubGrupo": 3,
                "idPadre": 6,
                "idTareaAnterior": null,
                "idSprint": 3,
                "sumillaTarea": "Subtarea 1",
                "descripcion": "Descripción de la subtarea 1",
                "fechaInicio": "2023-10-21",
                "fechaFin": "2023-10-23",
                "cantSubtareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 15,
                "usuarios": [
                    {
                        "idUsuario": 78
                    }
                ]
            }
        }
    ],
    "tareasPosteriores": [
        {
            "body": {
                "idCronograma": 1,
                "idTareaEstado": 2,
                "idSubGrupo": 3,
                "idPadre": 4,
                "idTareaAnterior": 7,
                "idSprint": 3,
                "sumillaTarea": "Tarea posterior 1",
                "descripcion": "Descripción de la tarea posterior 1",
                "fechaInicio": "2023-10-26",
                "fechaFin": "2023-10-28",
                "cantSubtareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 10,
                "usuarios": [
                    {
                        "idUsuario": 78
                    }
                ]
            }
        }
    ]
}