###
POST http://localhost:8080/api/proyecto/EDT/descargarExcelEDT
Content-Type: application/json

{
    "componentes":[
  {
    "idComponente": 96,
    "idElementoPadre": 1,
    "idEDT": 101,
    "descripcion": "Descripcion",
    "codigo": "1",
    "observaciones": "observaciones",
    "activo": 1,
    "idComponenteTags": null,
    "nombre": "sadg",
    "responsables": "sthsdt",
    "fechaInicio": "2023-11-08T05:00:00.000Z",
    "fechaFin": "2023-11-24T05:00:00.000Z",
    "recursos": "recursos",
    "hito": "hito",
    "entregables": [
      {
        "idEntregable": 64,
        "nombre": "papeleta",
        "idComponente": 96,
        "activo": 1
      }
    ],
    "criterios": [
      {
        "idComponenteCriterioDeAceptacion": 49,
        "idComponenteEDT": 96,
        "descripcion": "dfh",
        "activo": 1
      }
    ],
    "componentesHijos": [
      {
        "idComponente": 97,
        "idElementoPadre": 96,
        "idEDT": 101,
        "descripcion": "dfgn",
        "codigo": "1.1",
        "observaciones": "dfgn",
        "activo": 1,
        "idComponenteTags": null,
        "nombre": "dfgn",
        "responsables": "ascas",
        "fechaInicio": "2023-11-08T05:00:00.000Z",
        "fechaFin": "2023-11-30T05:00:00.000Z",
        "recursos": "dfgn",
        "hito": "dfgn",
        "entregables": [
          {
            "idEntregable": 65,
            "nombre": "ddddd",
            "idComponente": 97,
            "activo": 1
          }
        ],
        "criterios": [
          {
            "idComponenteCriterioDeAceptacion": 50,
            "idComponenteEDT": 97,
            "descripcion": "ascasc",
            "activo": 1
          }
        ],
        "componentesHijos": null,
        "nextSon": "1.1.1"
      }
    ],
    "nextSon": "1.2"
  }
]
}