POST http://localhost:3000/api/proyecto/insertarProyecto HTTP/1.1
Content-Type:  application/json

{
    "idUsuario": 77,
    "nombre": "Proyecto de darle mantenimiento a PUCP movil",
    "maxCantParticipantes": 8,
    "fechaInicio": null,
    "fechaFin": null
}

###

POST http://localhost:3000/api/proyecto/backlog/hu/eliminarHistoria HTTP/1.1
Content-Type:  application/json

{
    "idHistoriaDeUsuario" : 1
}

###


POST http://localhost:3000/api/herramientas/listarHerramientas HTTP/1.1
Content-Type:  application/json

{
}

###

POST http://localhost:8080/api/proyecto/EDT/3/insertarComponenteEDT HTTP/1.1
Content-Type:  application/json

{
  "idElementoPadre": 1,
  "idEDT": 2,
  "descripcion": "Component EDT description",
  "codigo": "EDT001",
  "observaciones": "Some observations",
  "nombre": "EDT Example",
  "responsables": "John Doe, Jane Smith",
  "fechaInicio": "2023-10-10",
  "fechaFin": "2023-11-10",
  "recursos": "Resource 1, Resource 2",
  "hito": "Project milestone",
  "criterioAceptacion": [
    "Criterio 1",
    "Criterio 2",
    "Criterio 3"
  ],
  "entregables": [
    "Entregable 1",
    "Entregable 2"
  ]
}

###


POST http://localhost:8080/api/usuario/listarUsuarios HTTP/1.1
Content-Type:  application/json

{
  "nombreCorreo": "ad"
}

###

POST http://localhost:3000/api/proyecto/listarProyectosPorNombre HTTP/1.1
Content-Type:  application/json

{
  "nombre": "#"
}

###

POST http://localhost:8080/api/proyecto/backlog/hu/insertarHistoriaDeUsuario HTTP/1.1
Content-Type:  application/json

{
  "idEpic": 5,
  "idPriority": 1,
  "idState": 1,
  "name": "Prueba",
  "como": "Prueba",
  "quiero": "Prueba",
  "para": "Prueba",
  "idUsuarioCreador": 83,
  "scenarioData": [
    {
      "scenario": "Escenario 1",
      "dadoQue": "Dado que llega el inicio del día laboral",
      "cuando": "Cuando un empleado marca su entrada",
      "entonces": "Entonces se registra la hora de entrada del empleado"
    },
    {
      "scenario": "Escenario 2",
      "dadoQue": "Dado que un empleado marca su salida",
      "cuando": "Cuando finaliza su jornada laboral",
      "entonces": "Entonces se registra la hora de salida del empleado"
    }
  ],
  "requirementData": [
    {
      "requirement": "Requerimiento 1: Registrar la asistencia de los empleados"
    },
    {
      "requirement": "Requerimiento 2: Generar informes de asistencia"
    }
  ]
}

###

POST http://localhost:8080/api/proyecto/EDT/listarComponenteEDT HTTP/1.1
Content-Type:  application/json

{
  "idComponente": "17"
}

###

POST http://localhost:8080/api/proyecto/backlog/hu/listarHistoriaDeUsuario HTTP/1.1
Content-Type:  application/json

{
  "idHistoriaDeUsuario": "17"
}

###

PUT http://localhost:8080/api/proyecto/backlog/hu/modificarHistoriaDeUsuario HTTP/1.1
Content-Type:  application/json

{
  "idHistoriaUsuario": 8,
  "idEpic": 1,
  "idPriority": 1,
  "idState": 1,
  "name": "Registro de Asistencia",
  "como": "Jefe del Proyecto",
  "quiero": "marcar el registro de asistencia de mis compañeros",
  "para": "llevar un control de su asistencia",
  "scenarioData": [
    {
      "idHistoriaCriterioDeAceptacion": 10,
      "scenario": "Escenario 1",
      "dadoQue": "Holae llega el inicio del día laboral",
      "cuando": "Holae un empleado marca su entrada",
      "entonces": "Entonces se registra la hora de entrada del empleado"
    },
    {
      "idHistoriaCriterioDeAceptacion": 11,
      "scenario": "Escenario 2",
      "dadoQue": "Holae que un empleado marca su salida",
      "cuando": "Holae finaliza su jornada laboral",
      "entonces": "Entonces se registra la hora de salida del empleado"
    }
  ],
  "requirementData": [
    {
      "idHistoriaRequisito": 15,
      "requirement": "Requerimiento 1: Holae la asistencia de los empleados"
    },
    {
      "idHistoriaRequisito": 16,
      "requirement": "Requerimiento 2: Holae informes de asistencia"
    }
  ]
}


###

GET http://localhost:8080/api/proyecto/backlog/hu/17/listarHistoriaDeUsuario HTTP/1.1
Content-Type:  application/json

### Insertar equipo (Backend) en proyecto

POST http://localhost:8080/api/proyecto/equipo/insertarEquipoYParticipantes HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 6,
  "nombre": "Backend",
  "descripcion": "Este es un equipo para el backend",
  "usuarios": [
    {
      "idUsuario": 78
    },
    {
      "idUsuario": 84
    }
  ]

}

###


GET http://localhost:8080/api/proyecto/equipo/test/1 HTTP/1.1


###

DELETE http://localhost:8080/api/proyecto/backlog/hu/eliminarEpica HTTP/1.1
Content-Type:  application/json

{
  "nombreEpica": "Epica 1"
}

###

GET http://localhost:8080/api/proyecto/backlog/45/listarBacklog HTTP/1.1
Content-Type:  application/json

{
}

###
POST http://localhost:8080/api/proyecto/backlog/hu/listarProductBacklog HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 45
}

###
POST http://localhost:8080/api/proyecto/backlog/hu/insertarEpica HTTP/1.1
Content-Type:  application/json

{
  "idProductBacklog": 1,
  "nombre": "Prueba"
}

###
POST http://localhost:8080/api/proyecto/ActaConstitucion/listarActaConstitucion HTTP/1.1
Content-Type:  application/json

{
  "idActaConstitucion": 11
}

###
GET http://localhost:8080/api/proyecto/ActaConstitucion/listarInteresados HTTP/1.1
Content-Type:  application/json

{
  "idActaConstitucion": 11
}

###
GET http://localhost:8080/api/proyecto/ActaConstitucion/listarHito HTTP/1.1
Content-Type:  application/json

{
  "idActaConstitucion": 11
}


###

POST http://localhost:8080/api/proyecto/cronograma/insertarTarea HTTP/1.1
Content-Type:  application/json

{
    "idCronograma": 1,
    "idTareaEstado": 2,
    "idSubGrupo": 3,
    "idPadre": 4,
    "idTareaAnterior": 5,
    "sumillaTarea": "Sumilla de la tarea",
    "descripcion": "Descripción detallada de la tarea",
    "fechaInicio": "2023-10-20",
    "fechaFin": "2023-10-25",
    "cantSubtareas": 2,
    "cantPosteriores": 1,
    "horasPlaneadas": 40,
    "usuarios": [
        {
            "idUsuario": 77
        },
        {
            "idUsuario": 78
        }
    ],
    "subTareas": [
        {
            "body": {
                "idCronograma": 1,
                "idTareaEstado": 2,
                "idSubGrupo": 3,
                "idPadre": 6,
                "idTareaAnterior": null,
                "sumillaTarea": "Subtarea 1",
                "descripcion": "Descripción de la subtarea 1",
                "fechaInicio": "2023-10-21",
                "fechaFin": "2023-10-23",
                "cantSubtareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 15,
                "usuarios": [
                    {
                        "idUsuario": 78
                    }
                ]
            }
        }
    ],
    "tareasPosteriores": [
        {
            "body": {
                "idCronograma": 1,
                "idTareaEstado": 2,
                "idSubGrupo": 3,
                "idPadre": 4,
                "idTareaAnterior": 7,
                "sumillaTarea": "Tarea posterior 1",
                "descripcion": "Descripción de la tarea posterior 1",
                "fechaInicio": "2023-10-26",
                "fechaFin": "2023-10-28",
                "cantSubtareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 10,
                "usuarios": [
                    {
                        "idUsuario": 78
                    }
                ]
            }
        }
    ]
}


###
GET http://localhost:8080/api/proyecto/cronograma/listarTareasXidProyecto/45 HTTP/1.1
Content-Type:  application/json

###


GET http://localhost:8080/api/proyecto/equipo/listarEquiposYParticipantes/59 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/presupuesto/listarMonedasTodas HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/presupuesto/listarTipoIngresosTodos  HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/presupuesto/listarTipoTransaccionTodos HTTP/1.1
Content-Type:  application/json

###

###
POST http://localhost:8080/api/proyecto/presupuesto/insertarLineaIngreso HTTP/1.1
Content-Type:  application/json

{
  "idIngreso": 4,
  "idMoneda": 1,
  "idTransaccionTipo": 2,
  "idIngresoTipo": 3,
  "descripcion": "Pago de servicios",
  "monto": 1500.50,
  "cantidad": 5,
  "fechaTransaccion": "2023-10-19"
}


###
POST http://localhost:8080/api/proyecto/presupuesto/insertarLineaEstimacionCosto HTTP/1.1
Content-Type:  application/json

{
  "idMoneda": 1, 
  "idProyecto": 50,
  "idPresupuesto": 4,  
  "descripcion": "Toy probando cambio de dropeo de tabla estimacion costo",
  "tarifaUnitaria": 100.00,  
  "cantidadRecurso": 3,  
  "subtotal": 300.00,  
  "fechaInicio": "2023-10-24" 
}

###
PUT http://localhost:8080/api/proyecto/presupuesto/modificarLineaEstimacionCosto HTTP/1.1
Content-Type: application/json

{
  "idLineaEstimacionCosto": 7,
  "idMoneda": 1, 
  "descripcion": "Nueva descripción modificada",
  "tarifaUnitaria": 150.00,  
  "cantidadRecurso": 4,  
  "subtotal": 600.00,  
  "fechaInicio": "2023-10-25" 
}


###
POST http://localhost:8080/api/proyecto/presupuesto/insertarLineaEgreso HTTP/1.1
Content-Type:  application/json

{
  "idPresupuesto": 1,  
  "idProyecto": 50,  
  "idMoneda": 1,  
  "idLineaEstimacionCosto": 3,  
  "descripcion": "Descripción de la línea de egreso",
  "costoReal": 1000.00,  
  "fechaRegistro": "2023-10-24",  
  "cantidad": 2  
}

###
GET http://localhost:8080/api/proyecto/presupuesto/listarLineasTodasXIdProyecto/50 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/presupuesto/listarLineasIngresoYEgresoXIdProyecto/50 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarCanales HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarFrecuencia HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarComunicacion/8 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarFormato HTTP/1.1
Content-Type:  application/json

###
POST http://localhost:8080/api/proyecto/presupuesto/insertarLineaIngreso HTTP/1.1
Content-Type:  application/json

{
  "idPresupuesto": 2,
  "idProyecto": 50,
  "idMoneda": 1,
  "descripcion": "Ejemplo de descripción uwu",
  "costoReal": 1234.56,
  "fechaRegistro": "2023-10-20",
  "cantidad": 789
}





###
GET http://localhost:8080/api/proyecto/presupuesto/listarLineaEstimacionCostoXNombreFechas/50/NULL/NULL/NULL HTTP/1.1


////////////////////////////
//Matriz de Comunicaciones//
////////////////////////////
###
POST http://localhost:8080/api/proyecto/matrizDeComunicaciones/insertarMatrizComunicacion HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 59,
  "idCanal": 1,
  "idFrecuencia": 1,
  "idFormato": 1,
  "sumillaInformacion": "Prueba 123",
  "detalleInformacion": "Prueba 123",
  "responsableDeComunicar": 1,
  "grupoReceptor": "Prueba 123"
}

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarMatrizComunicacion/59 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/listarUsuariosXdProyecto/58 HTTP/1.1
Content-Type:  application/json
###
DELETE http://localhost:8080/api/proyecto/matrizDeComunicaciones/eliminarComunicacion HTTP/1.1
Content-Type:  application/json

{
  "idComunicacion": 14
}

////////////////////////////
//  ACTA de CONSTITUCION  //
////////////////////////////

###LISTAR ACTA DE CONSTITUCION
GET http://localhost:8080/api/proyecto/ActaConstitucion/listarActaConstitucion/50 HTTP/1.1
Content-Type:  application/json

###MODIFICAR CAMPOS ACTA DE CONSTITUCION
PUT http://localhost:8080/api/proyecto/ActaConstitucion/modificarCampos HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 50,
  "nombreProyecto": "Hola123",
  "empresa": "Hola123",
  "cliente": "Hola123",
  "patrocinador": "Hola123",
  "gerente": "Hola123",
  "actaData": [
    {
      "idDetalle": 1,
      "idActaConstitucion": 11,
      "nombre": "Propósito y Justificación del Proyecto",
      "detalle": null,
      "activo": 1
    },
    {
      "idDetalle": 2,
      "idActaConstitucion": 11,
      "nombre": "Descripción del Proyecto y Entregables",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 3,
      "idActaConstitucion": 11,
      "nombre": "Presupuesto Estimado",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 4,
      "idActaConstitucion": 11,
      "nombre": "Premisas y Restricciones",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 5,
      "idActaConstitucion": 11,
      "nombre": "Riesgos Iniciales de Alto Nivel",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 6,
      "idActaConstitucion": 11,
      "nombre": "Requisitos de Aprobación del Proyecto",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 7,
      "idActaConstitucion": 11,
      "nombre": "Requerimientos de Alto Nivel",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 8,
      "idActaConstitucion": 11,
      "nombre": "Requerimientos del Producto",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 9,
      "idActaConstitucion": 11,
      "nombre": "Requerimientos del Proyecto",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 10,
      "idActaConstitucion": 11,
      "nombre": "Elaborado pro",
      "detalle": "Probando123",
      "activo": 1
    }
  ]
}
###CREAR CAMPO AC
POST http://localhost:8080/api/proyecto/ActaConstitucion/crearCampos HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 50,
  "nombreCampo": "Prueba",
  "detalleCampo": "Prueba"
}
###LISTAR INTERESADOS AC
GET http://localhost:8080/api/proyecto/ActaConstitucion/listarInteresados/50 HTTP/1.1
Content-Type:  application/json

###INSERTAR INTERESADOS AC
POST http://localhost:8080/api/proyecto/ActaConstitucion/insertarInteresado HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 50, 
  "nombre": "Hola123", 
  "cargo": "Hola123",  
  "organizacion": "Hola123"
}
}
###ELIMINAR CAMPO AC
DELETE http://localhost:8080/api/proyecto/ActaConstitucion/eliminarCampo HTTP/1.1
Content-Type:  application/json

{
  "idDetalle": 64
}

###ELIMINAR HITO AC
DELETE http://localhost:8080/api/proyecto/ActaConstitucion/eliminarHito HTTP/1.1
Content-Type:  application/json

{
  "idHito": 6
}

###ELIMINAR INTERESADO AC
DELETE http://localhost:8080/api/proyecto/ActaConstitucion/eliminarInteresado HTTP/1.1
Content-Type:  application/json

{
  "idInteresado": 3
}

###MODIFICAR INTERESADO AC
PUT http://localhost:8080/api/proyecto/ActaConstitucion/modificarInteresado HTTP/1.1
Content-Type:  application/json

{
  "idInteresado": 4,
  "nombre": "ProbarEliminar",
  "cargo": "Test",
  "organizacion": "idk"
}

////////////////////////////
//  CATALOGO DE RIESGOS   //
////////////////////////////

###LISTAR PROBABILIDAD
GET http://localhost:8080/api/proyecto/catalogoRiesgos/listarProbabilidades HTTP/1.1
Content-Type:  application/json

###LISTAR IMPACTO
GET http://localhost:8080/api/proyecto/catalogoRiesgos/listarImpacto HTTP/1.1
Content-Type:  application/json

###INSERTAR RIESGO
POST http://localhost:8080/api/proyecto/catalogoRiesgos/insertarRiesgo HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 64,
  "idProbabilidad": 3,
  "idImpacto": 3,
  "nombreRiesgo": "Hola123",
  "fechaIdentificacion": "2023-10-20",
  "duenoRiesgo": 88,
  "detalleRiesgo": "Hola123",
  "causaRiesgo": "Hola123",
  "impactoRiesgo": "Hola123",
  "estado": "Activo",
  "responsables": [
    {
      "id": 84,
      "nombres": "Victor",
      "apellidos": "Tong",
      "correoElectronico": "a20192310@pucp.edu.pe"
    },
    {
      "id": 77,
      "nombres": "Renzo Gabriel",
      "apellidos": "Pinto Quiroz",
      "correoElectronico": "admin.com"
    },
    {
      "id": 81,
      "nombres": "Andrea",
      "apellidos": "Gonzales",
      "correoElectronico": "andrea@pucp.edu.pe"
    }
  ],
  "planesRespuesta": [
    {
      "responsePlans": "Prbando"
    },
    {
      "responsePlans": "Tengo sueño xd"
    },
    {
      "responsePlans": "Son la 1AM"
    }
  ],
  "planesContigencia": [
    {
      "contingencyPlans": "Holaaa"
    },
    {
      "contingencyPlans": "Tengo sueño xd"
    },
    {
      "contingencyPlans": "Son la 1AM"
    }
  ]
}

###LISTAR RIESGOS
GET http://localhost:8080/api/proyecto/catalogoRiesgos/listarRiesgos/64 HTTP/1.1
Content-Type:  application/json

###LISTAR UN RIESGO
GET http://localhost:8080/api/proyecto/catalogoRiesgos/listarunRiesgo/7 HTTP/1.1
Content-Type:  application/json

###LISTAR UN RIESGO
GET http://localhost:8080/api/proyecto/presupuesto/listarLineasTodasXIdProyecto/50 HTTP/1.1
Content-Type:  application/json

###ELIMINAR UN RIESGO
DELETE http://localhost:8080/api/proyecto/catalogoRiesgos/eliminarRRC HTTP/1.1
Content-Type:  application/json

{
  "idRiesgo": 7
}

###ACTUALIZAR RCC UN RIESGO
DELETE http://localhost:8080/api/proyecto/catalogoRiesgos/eliminarRRC HTTP/1.1
Content-Type:  application/json

{
  "idRiesgo": 20,
  "idProbabilidad": 5,
  "idImpacto": 5,
  "nombreRiesgo": "Prueba1",
  "fechaIdentificacion": "2023-10-20",
  "duenoRiesgo": 97,
  "detalleRiesgo": "Prueba2",
  "causaRiesgo": "Prueba3",
  "impactoRiesgo": "Prueba4",
  "estado": "Activo",
  "responsables": [],
  "planesRespuesta": [
    {
      "idPlanRespuesta": 25,
      "responsePlans": "PruebaInsertar1"
    },
    {
      "idPlanRespuesta": 26,
      "responsePlans": "PruebaInsertar2"
    },
    {
      "idPlanRespuesta": 27,
      "responsePlans": "PruebaInsertar3"
    }
  ],
  "planesContingencia": [
    {
      "idPlanContingencia": 23,
      "contingencyPlans": "PruebaInsertar1"
    },
    {
      "idPlanContingencia": 24,
      "contingencyPlans": "PruebaInsertar2"
    },
    {
      "idPlanContingencia": 25,
      "contingencyPlans": "PruebaInsertar3"
    }
  ]
}


###
POST http://localhost:8080/api/proyecto/actaReunion/crearActaReunion HTTP/1.1
Content-Type: application/json

{
  "idProyecto": 78
}

###
POST http://localhost:8080/api/proyecto/actaReunion/crearLineaActaReunion HTTP/1.1
Content-Type: application/json


{
  "idActaReunion": 29,
  "nombreReunion": "Reunión de Planificación",
  "fechaReunion": "2023-11-01",
  "horaReunion": "10:00 AM",
  "nombreConvocante": "Juan Pérez",
  "motivo": "Discutir los detalles del proyecto",
  "temas": [
    {
      "descripcion": "Tema 1: Planificación del proyecto 2",
      "acuerdos": [
        {
          "descripcion": "Acuerdo 1: Definir los plazos del proyecto",
          "fechaObjetivo": "2023-11-10",
          "responsables": [
            {
              "idUsuarioXRolXProyecto": 2
            },
            {
              "idUsuarioXRolXProyecto": 4
            }
          ]
        }
      ]
    }
  ],
  "participantes": [
    {
      "idUsuarioXRolXProyecto": 2,
      "asistio": true
    }
  ],
  "comentarios": [
    {
      "descripcion": "Comentario 1: La reunión fue productiva"
    }
  ]
}



###
GET http://localhost:8080/api/proyecto/actaReunion/listarActaReunionXIdProyecto/78 HTTP/1.1
Content-Type: application/json
###
GET http://localhost:8080/api/proyecto/actaReunion/listarLineaActaReunionXIdActaReunion/5 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8080/api/proyecto/actaReunion/listarLineaActaReunionXIdLineaActaReunion/104 HTTP/1.1
Content-Type: application/json

////////////////////////////
//  AUTOEVALUACION        //
////////////////////////////
###CREAR AUTOEVALUACION AC
POST http://localhost:8080/api/proyecto/autoEvaluacion/crearAutoEvaluacion HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 173,
  "nombre": "Prueba",
  "criterio1": "Prueba1",
  "criterio2": "Prueba2",
  "criterio3": "Prueba3",
  "criterio4": "Prueba4",
  "fechaInicio": "2023-10-25",
  "fechaFin": "2023-10-26"
}

###LISTAR TODA AUTOEVALUACION
GET http://localhost:8080/api/proyecto/autoEvaluacion/listarTodasAutoEvaluacion/148 HTTP/1.1
Content-Type:  application/json

###LISTAR AUTOEVALUACION
GET http://localhost:8080/api/proyecto/autoEvaluacion/listarAutoEvaluacion/148/79 HTTP/1.1
Content-Type:  application/json

###ACTIVAR AUTOEVALUACION
PUT http://localhost:8080/api/proyecto/autoEvaluacion/activarAutoEvaluacion HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 148,
  "idAutoEvaluacionXProyecto": 7
}

###FINALIZAR AUTOEVALUACION
PUT http://localhost:8080/api/proyecto/autoEvaluacion/finalizarAutoEvaluacion HTTP/1.1
Content-Type:  application/json

{
  "idAutoEvaluacionXProyecto": 7
}

###LISTAR AUTOEVALUACION CON NOTAS
GET http://localhost:8080/api/proyecto/autoEvaluacion/listarAutoEvaluacionNotas/7 HTTP/1.1
Content-Type:  application/json


###

DELETE http://localhost:8080/api/proyecto/actaReunion/eliminarLineaActaReunionXIdLineaActaReunion HTTP/1.1
Content-Type:  application/json

{
  "idLineaActaReunion": 5
}

### GET

GET http://localhost:8080/api/proyecto/backlog/test/2 HTTP/1.1
Content-Type:  application/json


###

PUT http://localhost:8080/api/proyecto/presupuesto/modificarLineaEgreso HTTP/1.1
Content-Type: application/json

{
  "idLineaEgreso": 1,
  "idMoneda": 2,
  "idLineaEstimacionCosto": 3,
  "descripcion": "Descripción de la línea de egreso modificada",
  "costoReal": 1500.00,
  "fechaRegistro": "2023-10-25",
  "cantidad": 4
}

###
PUT http://localhost:8080/api/proyecto/presupuesto/modificarLineaEstimacionCosto HTTP/1.1
Content-Type: application/json

{
  "idLineaEstimacionCosto": 7,
  "idMoneda": 2,
  "descripcion": "Descripción de la línea de estimación de costo modificada",
  "tarifaUnitaria": 500.00,
  "cantidadRecurso": 3,
  "subtotal": 1500.00,
  "fechaInicio": "2023-10-25"
}

###ACTUALIZAR AUTOEVALUACION AC
PUT http://localhost:8080/api/proyecto/autoEvaluacion/actualizarAutoEvaluacion HTTP/1.1
Content-Type:  application/json

{
  "evaluados": [
    {
      "idUsuarioEvaluacion": 5,
      "idUsuario": 79,
      "nombreEvaluador": "Juan Angelo",
      "apellidoEvaluador": "Flores Rubio",
      "idUsuarioEvaluado": 79,
      "nombreEvaluado": "Juan Angelo",
      "apellidoEvaluado": "Flores Rubio",
      "activo": 1,
      "observaciones": null,
      "criterios": [
        {
          "idCriterioEvaluacion": 13,
          "idUsuarioEvaluacion": 5,
          "criterio": "Hola",
          "nota": 4,
          "activo": 1
        },
        {
          "idCriterioEvaluacion": 14,
          "idUsuarioEvaluacion": 5,
          "criterio": "Hola",
          "nota": 5,
          "activo": 1
        },
        {
          "idCriterioEvaluacion": 15,
          "idUsuarioEvaluacion": 5,
          "criterio": "Hola",
          "nota": 4,
          "activo": 1
        },
        {
          "idCriterioEvaluacion": 16,
          "idUsuarioEvaluacion": 5,
          "criterio": "Hola",
          "nota": 3,
          "activo": 1
        }
      ]
    }
  ]
}


//Listar interesados Catalogo de interesados
### GET
GET http://localhost:8080/api/proyecto/catalogoInteresados/listarInteresado/19 HTTP/1.1
Content-Type:  application/json

//Insertar interesados Catalogo de interesados
### POST
POST http://localhost:8080/api/proyecto/catalogoInteresados/insertarInteresado/ HTTP/1.1
Content-Type: application/json
{
  "cargo": "cargo",
  "idMoneda": 2,
  "idLineaEstimacionCosto": 3,
  "descripcion": "Descripción de la línea de egreso modificada",
  "costoReal": 1500.00,
  "fechaRegistro": "2023-10-25",
  "cantidad": 4
}


////////////////////////////
//Matriz de Responsabilidad//
////////////////////////////
//Listar responsabilidad rol x id proyecto
### GET
GET http://localhost:8080/api/proyecto/matrizResponsabilidad/listarResponsabilidad/183 HTTP/1.1
Content-Type: application/json

### GET
GET http://localhost:8080/api/proyecto/matrizResponsabilidad/listarRol/156 HTTP/1.1
Content-Type: application/json

### GET
GET http://localhost:8080/api/proyecto/matrizResponsabilidad/listarEntregables/178 HTTP/1.1
Content-Type: application/json