###
POST http://localhost:8080/api/proyecto/plantillas/guardarPlantillaAC HTTP/1.1
Content-Type: application/json

{
  "idActaConstitucion": 11, 
  "idUsuario": 84,
  "nombrePlantilla": "test"
}

###
GET http://localhost:8080/api/proyecto/plantillas/listarPlantillasAC/84 HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:8080/api/proyecto/plantillas/eliminarPlantillaAC HTTP/1.1
Content-Type: application/json

{
  "idPlantillaAC": 3
}

###
PUT http://localhost:8080/api/proyecto/plantillas/seleccionarPlantillaAC HTTP/1.1
Content-Type: application/json

{
  "idActaConstitucion": ,
  "idPlantillaAC": 
}

###
POST http://localhost:8080/api/proyecto/plantillas/guardarPlantillaKanban HTTP/1.1
Content-Type: application/json

{
  "idProyecto": 156,
  "idUsuario": 97,
  "nombrePlantilla": "test"
}

###
GET http://localhost:8080/api/proyecto/plantillas/listarPlantillasKanban/97 HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:8080/api/proyecto/plantillas/eliminarPlantillaKanban HTTP/1.1
Content-Type: application/json

{
  "idPlantillaKanban": 2
}

###
PUT http://localhost:8080/api/proyecto/plantillas/seleccionarPlantillaKanban HTTP/1.1
Content-Type: application/json

{
  "idProyecto": ,
  "idPlantillaKanban": 
}

###
GET http://localhost:8080/api/proyecto/plantillas/listarPlantillasKanbanXNombre/97/a HTTP/1.1
Content-Type: application/json