###
POST http://localhost:8080/api/proyecto/reporte/crearExcelListaParticipantes HTTP/1.1
Content-Type: application/json

{

  "nombreEquipo": "When eres",
  "participantes": [
    {
      "nombres": "Diego",
      "apellidos": "Veramendi Malpartida",
      "correoElectronico": "v.dvm.dvm@gmail.com",
      "nombreRol": "Líder"
    },
    {
      "nombres": "BRUCE ANTHONY",
      "apellidos": "ESTRADA MELGAREJO",
      "correoElectronico": "a20203298@pucp.edu.pe",
      "nombreRol": "Miembro"
    },
    {
      "nombres": "GABRIEL OMAR",
      "apellidos": "DURAN RUIZ",
      "correoElectronico": "a20203371@pucp.edu.pe",
      "nombreRol": "Miembro"
    },
    {
      "nombres": "CHRISTIAN SEBASTIAN",
      "apellidos": "CHIRA MALLQUI",
      "correoElectronico": "s.chira@pucp.edu.pe",
      "nombreRol": "Miembro"
    }
  ]
}