
###
GET http://localhost:8080/api/proyecto/reporte/obtenerJSONReporteEntregableXFileId/1nOpP03eSsiSEkidUm6_fP-nhsSjweNbx HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8080/api/proyecto/reporte/descargarExcelReporteEntregableXFileId HTTP/1.1
Content-Type: application/json

{
  "fileId": "1ePgFEKpZoQ4EKbVqMeEk1ViJmmf_Jchs"
}

###
POST http://localhost:8080/api/proyecto/reporte/subirReporteEntregableJSON HTTP/1.1
Content-Type: application/json

{
  "idProyecto": 178,
  "nombre": "probando reporte entregables",
  "entregables":[
      {
        "idEntregable": 22,
        "nombre": "ENTREGABLE GOOOO",
        "idComponente": 63,
        "activo": 1,
        "ComponenteEDTNombre": "COMPONENTE DE PRUEBA",
        "descripcion": "LA DESCRIPCION PRUEBA",
        "hito": "CASCASC",
        "fechaInicio": "2023-11-15T05:00:00.000Z",
        "fechaFin": "2023-11-29T05:00:00.000Z",
        "tareasEntregable": [
            {
                "idTarea": 178,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "onnoSIIIIIIIIIIIIIIIII",
                "descripcion": "onon",
                "fechaInicio": "2023-11-02T05:00:00.000Z",
                "fechaFin": "2023-11-17T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-02T05:00:00.000Z",
                "idTareaEstado": 2,
                "nombreTareaEstado": "En progreso",
                "colorTareaEstado": "primary",
                "esPosterior": 0,
                "idEntregable": 22,
                "usuarios": [
                    {
                        "idUsuario": 97,
                        "nombres": "BRUCE ANTHONY",
                        "apellidos": "ESTRADA MELGAREJO",
                        "correoElectronico": "a20203298@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJfDJJnt4CClfOWItoYOykKhkSPpobVB82pkxKw7MAIOQ=s96-c"
                    },
                    {
                        "idUsuario": 112,
                        "nombres": "rgpq25",
                        "apellidos": "pinto",
                        "correoElectronico": "renzopinto25@gmail.com",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJrt63rMLATn04gpvY9DXaY3w9Qs9fxJUPlKsOjnjMo=s96-c"
                    }
                ],
                "equipo": null
            },
            {
                "idTarea": 210,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "Tener el mejor UX",
                "descripcion": "descripcion",
                "fechaInicio": "2023-11-01T05:00:00.000Z",
                "fechaFin": "2023-11-24T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-03T05:00:00.000Z",
                "idTareaEstado": 4,
                "nombreTareaEstado": "Finalizado",
                "colorTareaEstado": "success",
                "esPosterior": 0,
                "idEntregable": 22,
                "usuarios": [
                    {
                        "idUsuario": 97,
                        "nombres": "BRUCE ANTHONY",
                        "apellidos": "ESTRADA MELGAREJO",
                        "correoElectronico": "a20203298@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJfDJJnt4CClfOWItoYOykKhkSPpobVB82pkxKw7MAIOQ=s96-c"
                    },
                    {
                        "idUsuario": 77,
                        "nombres": "Renzo Gabriel",
                        "apellidos": "Pinto Quiroz",
                        "correoElectronico": "admin.com",
                        "imgLink": null
                    },
                    {
                        "idUsuario": 95,
                        "nombres": "RENZO GABRIEL",
                        "apellidos": "PINTO QUIROZ",
                        "correoElectronico": "a20201491@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocI1Jw8tcRQyaf25KtKL3TeCGqzTx3mgSsMz_lbjDgQxyA=s96-c"
                    },
                    {
                        "idUsuario": 102,
                        "nombres": "DIEGO JAVIER KITAROU",
                        "apellidos": "IWASAKI MOREYRA",
                        "correoElectronico": "a20201540@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocKRRgelekIYLm0bPYScUwscQuOhl1lR6LVs8JjTAWQo=s96-c"
                    }
                ],
                "equipo": null
            },
            {
                "idTarea": 211,
                "idEquipo": 99,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "Exposición Sprint 3",
                "descripcion": "Exposición del avance del Sprint 3",
                "fechaInicio": "2023-11-03T05:00:00.000Z",
                "fechaFin": "2023-11-03T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-03T05:00:00.000Z",
                "idTareaEstado": 2,
                "nombreTareaEstado": "En progreso",
                "colorTareaEstado": "primary",
                "esPosterior": 0,
                "idEntregable": 22,
                "equipo": {
                    "idEquipo": 99,
                    "idProyecto": 156,
                    "nombre": "PruebaDailyMeeting",
                    "fechaCreacion": "2023-11-01T05:00:00.000Z",
                    "activo": 1,
                    "participantes": []
                },
                "usuarios": []
            },
            {
                "idTarea": 230,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "acasc",
                "descripcion": "acasc",
                "fechaInicio": "2023-11-07T05:00:00.000Z",
                "fechaFin": "2023-11-13T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-07T05:00:00.000Z",
                "idTareaEstado": 1,
                "nombreTareaEstado": "No iniciado",
                "colorTareaEstado": "default",
                "esPosterior": 0,
                "idEntregable": 22,
                "usuarios": [
                    {
                        "idUsuario": 102,
                        "nombres": "DIEGO JAVIER KITAROU",
                        "apellidos": "IWASAKI MOREYRA",
                        "correoElectronico": "a20201540@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocKRRgelekIYLm0bPYScUwscQuOhl1lR6LVs8JjTAWQo=s96-c"
                    }
                ],
                "equipo": null
            },
            {
                "idTarea": 231,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "tarea en 0",
                "descripcion": "cacsa",
                "fechaInicio": "2023-11-01T05:00:00.000Z",
                "fechaFin": "2023-11-16T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-07T05:00:00.000Z",
                "idTareaEstado": 1,
                "nombreTareaEstado": "No iniciado",
                "colorTareaEstado": "default",
                "esPosterior": 0,
                "idEntregable": 22,
                "usuarios": [
                    {
                        "idUsuario": 95,
                        "nombres": "RENZO GABRIEL",
                        "apellidos": "PINTO QUIROZ",
                        "correoElectronico": "a20201491@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocI1Jw8tcRQyaf25KtKL3TeCGqzTx3mgSsMz_lbjDgQxyA=s96-c"
                    },
                    {
                        "idUsuario": 102,
                        "nombres": "DIEGO JAVIER KITAROU",
                        "apellidos": "IWASAKI MOREYRA",
                        "correoElectronico": "a20201540@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocKRRgelekIYLm0bPYScUwscQuOhl1lR6LVs8JjTAWQo=s96-c"
                    }
                ],
                "equipo": null
            },
            {
                "idTarea": 237,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "nueva tarea",
                "descripcion": "descrip",
                "fechaInicio": "2023-10-31T05:00:00.000Z",
                "fechaFin": "2023-11-22T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 1,
                "fechaUltimaModificacionEstado": "2023-11-08T05:00:00.000Z",
                "idTareaEstado": 1,
                "nombreTareaEstado": "No iniciado",
                "colorTareaEstado": "default",
                "esPosterior": 0,
                "idEntregable": 22,
                "usuarios": [
                    {
                        "idUsuario": 106,
                        "nombres": "AUGUSTO VICTOR",
                        "apellidos": "TONG YANG",
                        "correoElectronico": "avtong@pucp.edu.pe",
                        "imgLink": null
                    }
                ],
                "equipo": null
            }
        ],
        "barProgress": "16.67",
        "colorState": "warning",
        "contribuyentes": [
            {
                "idContribuyente": 1,
                "usuario": {
                    "idUsuario": 97,
                    "nombres": "BRUCE ANTHONY",
                    "apellidos": "ESTRADA MELGAREJO",
                    "correoElectronico": "a20203298@pucp.edu.pe",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJfDJJnt4CClfOWItoYOykKhkSPpobVB82pkxKw7MAIOQ=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 2,
                "porcentajeTotal": 12.5
            },
            {
                "idContribuyente": 2,
                "usuario": {
                    "idUsuario": 112,
                    "nombres": "rgpq25",
                    "apellidos": "pinto",
                    "correoElectronico": "renzopinto25@gmail.com",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJrt63rMLATn04gpvY9DXaY3w9Qs9fxJUPlKsOjnjMo=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 1,
                "porcentajeTotal": 8.333333333333332
            },
            {
                "idContribuyente": 3,
                "usuario": {
                    "idUsuario": 77,
                    "nombres": "Renzo Gabriel",
                    "apellidos": "Pinto Quiroz",
                    "correoElectronico": "admin.com",
                    "imgLink": null
                },
                "equipo": null,
                "tareasAsignadas": 1,
                "porcentajeTotal": 4.166666666666666
            },
            {
                "idContribuyente": 4,
                "usuario": {
                    "idUsuario": 95,
                    "nombres": "RENZO GABRIEL",
                    "apellidos": "PINTO QUIROZ",
                    "correoElectronico": "a20201491@pucp.edu.pe",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocI1Jw8tcRQyaf25KtKL3TeCGqzTx3mgSsMz_lbjDgQxyA=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 2,
                "porcentajeTotal": 12.5
            },
            {
                "idContribuyente": 5,
                "usuario": {
                    "idUsuario": 102,
                    "nombres": "DIEGO JAVIER KITAROU",
                    "apellidos": "IWASAKI MOREYRA",
                    "correoElectronico": "a20201540@pucp.edu.pe",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocKRRgelekIYLm0bPYScUwscQuOhl1lR6LVs8JjTAWQo=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 3,
                "porcentajeTotal": 29.166666666666664
            },
            {
                "idContribuyente": 6,
                "usuario": null,
                "equipo": {
                    "idEquipo": 99,
                    "idProyecto": 156,
                    "nombre": "PruebaDailyMeeting",
                    "fechaCreacion": "2023-11-01T05:00:00.000Z",
                    "activo": 1,
                    "participantes": []
                },
                "tareasAsignadas": 1,
                "porcentajeTotal": 16.666666666666664
            },
            {
                "idContribuyente": 7,
                "usuario": {
                    "idUsuario": 106,
                    "nombres": "AUGUSTO VICTOR",
                    "apellidos": "TONG YANG",
                    "correoElectronico": "avtong@pucp.edu.pe",
                    "imgLink": null
                },
                "equipo": null,
                "tareasAsignadas": 1,
                "porcentajeTotal": 16.666666666666664
            }
        ]
    },
    {
        "idEntregable": 23,
        "nombre": "agregando un entregable!!",
        "idComponente": 64,
        "activo": 1,
        "ComponenteEDTNombre": "otro componente",
        "descripcion": "hola",
        "hito": "hola",
        "fechaInicio": "2023-11-01T05:00:00.000Z",
        "fechaFin": "2023-11-15T05:00:00.000Z",
        "tareasEntregable": [
            {
                "idTarea": 197,
                "idEquipo": 91,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "tarea after sprint",
                "descripcion": "cascas",
                "fechaInicio": "2023-11-14T05:00:00.000Z",
                "fechaFin": "2023-11-20T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-03T05:00:00.000Z",
                "idTareaEstado": 3,
                "nombreTareaEstado": "Atrasado",
                "colorTareaEstado": "danger",
                "esPosterior": 0,
                "idEntregable": 23,
                "equipo": {
                    "idEquipo": 91,
                    "idProyecto": 156,
                    "nombre": "PruebaConValidaciones",
                    "fechaCreacion": "2023-10-30T05:00:00.000Z",
                    "activo": 1,
                    "participantes": []
                },
                "usuarios": []
            },
            {
                "idTarea": 204,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "test",
                "descripcion": "posterop!",
                "fechaInicio": "2023-11-16T05:00:00.000Z",
                "fechaFin": "2023-11-22T05:00:00.000Z",
                "cantSubTareas": null,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-03T05:00:00.000Z",
                "idTareaEstado": 1,
                "nombreTareaEstado": "No iniciado",
                "colorTareaEstado": "default",
                "esPosterior": 0,
                "idEntregable": 23,
                "usuarios": [
                    {
                        "idUsuario": 97,
                        "nombres": "BRUCE ANTHONY",
                        "apellidos": "ESTRADA MELGAREJO",
                        "correoElectronico": "a20203298@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJfDJJnt4CClfOWItoYOykKhkSPpobVB82pkxKw7MAIOQ=s96-c"
                    },
                    {
                        "idUsuario": 95,
                        "nombres": "RENZO GABRIEL",
                        "apellidos": "PINTO QUIROZ",
                        "correoElectronico": "a20201491@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocI1Jw8tcRQyaf25KtKL3TeCGqzTx3mgSsMz_lbjDgQxyA=s96-c"
                    }
                ],
                "equipo": null
            },
            {
                "idTarea": 209,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "Generar Historias de usaruio",
                "descripcion": "cacascascas",
                "fechaInicio": "2023-11-13T05:00:00.000Z",
                "fechaFin": "2023-11-30T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-03T05:00:00.000Z",
                "idTareaEstado": 1,
                "nombreTareaEstado": "No iniciado",
                "colorTareaEstado": "default",
                "esPosterior": 0,
                "idEntregable": 23,
                "usuarios": [
                    {
                        "idUsuario": 97,
                        "nombres": "BRUCE ANTHONY",
                        "apellidos": "ESTRADA MELGAREJO",
                        "correoElectronico": "a20203298@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJfDJJnt4CClfOWItoYOykKhkSPpobVB82pkxKw7MAIOQ=s96-c"
                    },
                    {
                        "idUsuario": 93,
                        "nombres": "Diego Gustavo",
                        "apellidos": "Veramendi Malpartida",
                        "correoElectronico": "veramendi.diego@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJPVGYJZsx94AqeoVQXBVraWBlIpH3CHnmPRQ7nIooe9PA=s96-c"
                    },
                    {
                        "idUsuario": 96,
                        "nombres": "JUAN ANGELO",
                        "apellidos": "FLORES RUBIO",
                        "correoElectronico": "angelo.flores@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocLWS53LV_YEk7R075wQoeLMJZ7shVi5xzY7MXVFIMu5V5k=s96-c"
                    },
                    {
                        "idUsuario": 102,
                        "nombres": "DIEGO JAVIER KITAROU",
                        "apellidos": "IWASAKI MOREYRA",
                        "correoElectronico": "a20201540@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocKRRgelekIYLm0bPYScUwscQuOhl1lR6LVs8JjTAWQo=s96-c"
                    }
                ],
                "equipo": null
            },
            {
                "idTarea": 232,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "intentando insertar en To do",
                "descripcion": "cacasc",
                "fechaInicio": "2023-11-03T05:00:00.000Z",
                "fechaFin": "2023-11-10T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-07T05:00:00.000Z",
                "idTareaEstado": 1,
                "nombreTareaEstado": "No iniciado",
                "colorTareaEstado": "default",
                "esPosterior": 0,
                "idEntregable": 23,
                "usuarios": [
                    {
                        "idUsuario": 95,
                        "nombres": "RENZO GABRIEL",
                        "apellidos": "PINTO QUIROZ",
                        "correoElectronico": "a20201491@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocI1Jw8tcRQyaf25KtKL3TeCGqzTx3mgSsMz_lbjDgQxyA=s96-c"
                    },
                    {
                        "idUsuario": 102,
                        "nombres": "DIEGO JAVIER KITAROU",
                        "apellidos": "IWASAKI MOREYRA",
                        "correoElectronico": "a20201540@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocKRRgelekIYLm0bPYScUwscQuOhl1lR6LVs8JjTAWQo=s96-c"
                    }
                ],
                "equipo": null
            },
            {
                "idTarea": 233,
                "idEquipo": null,
                "idPadre": null,
                "idTareaAnterior": null,
                "sumillaTarea": "nuevo to do",
                "descripcion": "descripc",
                "fechaInicio": "2023-11-01T05:00:00.000Z",
                "fechaFin": "2023-11-10T05:00:00.000Z",
                "cantSubTareas": 0,
                "cantPosteriores": 0,
                "horasPlaneadas": 4,
                "fechaUltimaModificacionEstado": "2023-11-07T05:00:00.000Z",
                "idTareaEstado": 1,
                "nombreTareaEstado": "No iniciado",
                "colorTareaEstado": "default",
                "esPosterior": 0,
                "idEntregable": 23,
                "usuarios": [
                    {
                        "idUsuario": 102,
                        "nombres": "DIEGO JAVIER KITAROU",
                        "apellidos": "IWASAKI MOREYRA",
                        "correoElectronico": "a20201540@pucp.edu.pe",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocKRRgelekIYLm0bPYScUwscQuOhl1lR6LVs8JjTAWQo=s96-c"
                    },
                    {
                        "idUsuario": 112,
                        "nombres": "rgpq25",
                        "apellidos": "pinto",
                        "correoElectronico": "renzopinto25@gmail.com",
                        "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJrt63rMLATn04gpvY9DXaY3w9Qs9fxJUPlKsOjnjMo=s96-c"
                    }
                ],
                "equipo": null
            }
        ],
        "barProgress": "0.00",
        "colorState": "danger",
        "contribuyentes": [
            {
                "idContribuyente": 1,
                "usuario": null,
                "equipo": {
                    "idEquipo": 91,
                    "idProyecto": 156,
                    "nombre": "PruebaConValidaciones",
                    "fechaCreacion": "2023-10-30T05:00:00.000Z",
                    "activo": 1,
                    "participantes": []
                },
                "tareasAsignadas": 1,
                "porcentajeTotal": 20
            },
            {
                "idContribuyente": 2,
                "usuario": {
                    "idUsuario": 97,
                    "nombres": "BRUCE ANTHONY",
                    "apellidos": "ESTRADA MELGAREJO",
                    "correoElectronico": "a20203298@pucp.edu.pe",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJfDJJnt4CClfOWItoYOykKhkSPpobVB82pkxKw7MAIOQ=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 2,
                "porcentajeTotal": 15.000000000000002
            },
            {
                "idContribuyente": 3,
                "usuario": {
                    "idUsuario": 95,
                    "nombres": "RENZO GABRIEL",
                    "apellidos": "PINTO QUIROZ",
                    "correoElectronico": "a20201491@pucp.edu.pe",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocI1Jw8tcRQyaf25KtKL3TeCGqzTx3mgSsMz_lbjDgQxyA=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 2,
                "porcentajeTotal": 20
            },
            {
                "idContribuyente": 4,
                "usuario": {
                    "idUsuario": 93,
                    "nombres": "Diego Gustavo",
                    "apellidos": "Veramendi Malpartida",
                    "correoElectronico": "veramendi.diego@pucp.edu.pe",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJPVGYJZsx94AqeoVQXBVraWBlIpH3CHnmPRQ7nIooe9PA=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 1,
                "porcentajeTotal": 5
            },
            {
                "idContribuyente": 5,
                "usuario": {
                    "idUsuario": 96,
                    "nombres": "JUAN ANGELO",
                    "apellidos": "FLORES RUBIO",
                    "correoElectronico": "angelo.flores@pucp.edu.pe",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocLWS53LV_YEk7R075wQoeLMJZ7shVi5xzY7MXVFIMu5V5k=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 1,
                "porcentajeTotal": 5
            },
            {
                "idContribuyente": 6,
                "usuario": {
                    "idUsuario": 102,
                    "nombres": "DIEGO JAVIER KITAROU",
                    "apellidos": "IWASAKI MOREYRA",
                    "correoElectronico": "a20201540@pucp.edu.pe",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocKRRgelekIYLm0bPYScUwscQuOhl1lR6LVs8JjTAWQo=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 3,
                "porcentajeTotal": 25
            },
            {
                "idContribuyente": 7,
                "usuario": {
                    "idUsuario": 112,
                    "nombres": "rgpq25",
                    "apellidos": "pinto",
                    "correoElectronico": "renzopinto25@gmail.com",
                    "imgLink": "https://lh3.googleusercontent.com/a/ACg8ocJrt63rMLATn04gpvY9DXaY3w9Qs9fxJUPlKsOjnjMo=s96-c"
                },
                "equipo": null,
                "tareasAsignadas": 1,
                "porcentajeTotal": 10
            }
        ]
    }
  ]
}