POST http://localhost:3000/api/proyecto/insertarProyecto HTTP/1.1
Content-Type:  application/json

{
    "idUsuario": 77,
    "nombre": "Proyecto de darle mantenimiento a PUCP movil",
    "maxCantParticipantes": 8,
    "fechaInicio": null,
    "fechaFin": null
}

###

POST http://localhost:3000/api/proyecto/backlog/hu/eliminarHistoria HTTP/1.1
Content-Type:  application/json

{
    "idHistoriaDeUsuario" : 1
}

###


POST http://localhost:3000/api/herramientas/listarHerramientas HTTP/1.1
Content-Type:  application/json

{
}

###

POST http://localhost:8080/api/proyecto/EDT/3/insertarComponenteEDT HTTP/1.1
Content-Type:  application/json

{
  "idElementoPadre": 1,
  "idEDT": 2,
  "descripcion": "Component EDT description",
  "codigo": "EDT001",
  "observaciones": "Some observations",
  "nombre": "EDT Example",
  "responsables": "John Doe, Jane Smith",
  "fechaInicio": "2023-10-10",
  "fechaFin": "2023-11-10",
  "recursos": "Resource 1, Resource 2",
  "hito": "Project milestone",
  "criterioAceptacion": [
    "Criterio 1",
    "Criterio 2",
    "Criterio 3"
  ],
  "entregables": [
    "Entregable 1",
    "Entregable 2"
  ]
}

###


POST http://localhost:8080/api/usuario/listarUsuarios HTTP/1.1
Content-Type:  application/json

{
  "nombreCorreo": "ad"
}

###

POST http://localhost:3000/api/proyecto/listarProyectosPorNombre HTTP/1.1
Content-Type:  application/json

{
  "nombre": "#"
}

###

POST http://localhost:8080/api/proyecto/backlog/hu/insertarHistoriaDeUsuario HTTP/1.1
Content-Type:  application/json

{
  "idEpic": 5,
  "idPriority": 1,
  "idState": 1,
  "name": "Prueba",
  "como": "Prueba",
  "quiero": "Prueba",
  "para": "Prueba",
  "idUsuarioCreador": 83,
  "scenarioData": [
    {
      "scenario": "Escenario 1",
      "dadoQue": "Dado que llega el inicio del día laboral",
      "cuando": "Cuando un empleado marca su entrada",
      "entonces": "Entonces se registra la hora de entrada del empleado"
    },
    {
      "scenario": "Escenario 2",
      "dadoQue": "Dado que un empleado marca su salida",
      "cuando": "Cuando finaliza su jornada laboral",
      "entonces": "Entonces se registra la hora de salida del empleado"
    }
  ],
  "requirementData": [
    {
      "requirement": "Requerimiento 1: Registrar la asistencia de los empleados"
    },
    {
      "requirement": "Requerimiento 2: Generar informes de asistencia"
    }
  ]
}

###

POST http://localhost:8080/api/proyecto/EDT/listarComponenteEDT HTTP/1.1
Content-Type:  application/json

{
  "idComponente": "17"
}

###

POST http://localhost:8080/api/proyecto/backlog/hu/listarHistoriaDeUsuario HTTP/1.1
Content-Type:  application/json

{
  "idHistoriaDeUsuario": "17"
}

###

PUT http://localhost:8080/api/proyecto/backlog/hu/modificarHistoriaDeUsuario HTTP/1.1
Content-Type:  application/json

{
  "idHistoriaUsuario": 8,
  "idEpic": 1,
  "idPriority": 1,
  "idState": 1,
  "name": "Registro de Asistencia",
  "como": "Jefe del Proyecto",
  "quiero": "marcar el registro de asistencia de mis compañeros",
  "para": "llevar un control de su asistencia",
  "scenarioData": [
    {
      "idHistoriaCriterioDeAceptacion": 10,
      "scenario": "Escenario 1",
      "dadoQue": "Holae llega el inicio del día laboral",
      "cuando": "Holae un empleado marca su entrada",
      "entonces": "Entonces se registra la hora de entrada del empleado"
    },
    {
      "idHistoriaCriterioDeAceptacion": 11,
      "scenario": "Escenario 2",
      "dadoQue": "Holae que un empleado marca su salida",
      "cuando": "Holae finaliza su jornada laboral",
      "entonces": "Entonces se registra la hora de salida del empleado"
    }
  ],
  "requirementData": [
    {
      "idHistoriaRequisito": 15,
      "requirement": "Requerimiento 1: Holae la asistencia de los empleados"
    },
    {
      "idHistoriaRequisito": 16,
      "requirement": "Requerimiento 2: Holae informes de asistencia"
    }
  ]
}


###

GET http://localhost:8080/api/proyecto/backlog/hu/17/listarHistoriaDeUsuario HTTP/1.1
Content-Type:  application/json

### Insertar equipo (Backend) en proyecto

POST http://localhost:8080/api/proyecto/equipo/insertarEquipoYParticipantes HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 6,
  "nombre": "Backend",
  "descripcion": "Este es un equipo para el backend",
  "usuarios": [
    {
      "idUsuario": 78
    },
    {
      "idUsuario": 84
    }
  ]

}

###


GET http://localhost:8080/api/proyecto/equipo/test/1 HTTP/1.1


###

DELETE http://localhost:8080/api/proyecto/backlog/hu/eliminarEpica HTTP/1.1
Content-Type:  application/json

{
  "nombreEpica": "Epica 1"
}

###

GET http://localhost:8080/api/proyecto/backlog/45/listarBacklog HTTP/1.1
Content-Type:  application/json

{
}

###
POST http://localhost:8080/api/proyecto/backlog/hu/listarProductBacklog HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 45
}

###
POST http://localhost:8080/api/proyecto/backlog/hu/insertarEpica HTTP/1.1
Content-Type:  application/json

{
  "idProductBacklog": 1,
  "nombre": "Prueba"
}

###
POST http://localhost:8080/api/proyecto/ActaConstitucion/listarActaConstitucion HTTP/1.1
Content-Type:  application/json

{
  "idActaConstitucion": 11
}

###
GET http://localhost:8080/api/proyecto/ActaConstitucion/listarInteresados HTTP/1.1
Content-Type:  application/json

{
  "idActaConstitucion": 11
}

###
GET http://localhost:8080/api/proyecto/ActaConstitucion/listarHito HTTP/1.1
Content-Type:  application/json

{
  "idActaConstitucion": 11
}


###

POST http://localhost:8080/api/proyecto/cronograma/insertarTarea HTTP/1.1
Content-Type:  application/json


{
    "idCronograma": 6,
    "idSubGrupo": null,
    "idPadre": null,
    "idTareaAnterior": null,
    "sumillaTarea": "Ejemplo de tarea",
    "descripcion": "Esta es una descripción detallada de la tarea.",
    "fechaInicio": "2023-10-17",
    "fechaFin": "2023-11-17",
    "cantSubTareas": 5,
    "cantPosteriores": 2,
    "horasPlaneadas": "02:00:00",
    "activo": 1
}

###

GET http://localhost:8080/api/proyecto/cronograma/listarTareasXidProyecto/45 HTTP/1.1
Content-Type:  application/json

###


GET http://localhost:8080/api/proyecto/equipo/listarEquiposYParticipantes/4 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/presupuesto/listarMonedasTodas HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/presupuesto/listarTipoIngresosTodos  HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/presupuesto/listarTipoTransaccionTodos HTTP/1.1
Content-Type:  application/json

###

###
POST http://localhost:8080/api/proyecto/presupuesto/insertarLineaIngreso HTTP/1.1
Content-Type:  application/json

{
  "idIngreso": 4,
  "idMoneda": 1,
  "idTransaccionTipo": 2,
  "idIngresoTipo": 3,
  "descripcion": "Pago de servicios",
  "monto": 1500.50,
  "cantidad": 5,
  "fechaTransaccion": "2023-10-19"
}


###
GET http://localhost:8080/api/proyecto/presupuesto/listarLineasTodas/50 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarCanales HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarFrecuencia HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarComunicacion/8 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarFormato HTTP/1.1
Content-Type:  application/json

###
POST http://localhost:8080/api/proyecto/presupuesto/insertarLineaIngreso HTTP/1.1
Content-Type:  application/json

{
  "idPresupuesto": 2,
  "idProyecto": 50,
  "idMoneda": 1,
  "descripcion": "Ejemplo de descripción uwu",
  "costoReal": 1234.56,
  "fechaRegistro": "2023-10-20",
  "cantidad": 789
}



###
GET http://localhost:8080/api/proyecto/presupuesto/listarLineaEgresoXNombreFechas/50/NULL/NULL/NULL HTTP/1.1
Content-Type:  application/json
###
GET http://localhost:8080/api/proyecto/presupuesto/listarLineaIngresoXNombreFechas/50/NULL/NULL/NULL HTTP/1.1
Content-Type:  application/json
###
GET http://localhost:8080/api/proyecto/presupuesto/listarLineaEstimacionCostoXNombreFechas/50/NULL/NULL/NULL HTTP/1.1


////////////////////////////
//Matriz de Comunicaciones//
////////////////////////////
###
POST http://localhost:8080/api/proyecto/matrizDeComunicaciones/insertarMatrizComunicacion HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 59,
  "idCanal": 1,
  "idFrecuencia": 1,
  "idFormato": 1,
  "sumillaInformacion": "Prueba 123",
  "detalleInformacion": "Prueba 123",
  "responsableDeComunicar": 1,
  "grupoReceptor": "Prueba 123"
}

###
GET http://localhost:8080/api/proyecto/matrizDeComunicaciones/listarMatrizComunicacion/59 HTTP/1.1
Content-Type:  application/json

###
GET http://localhost:8080/api/proyecto/listarUsuariosXdProyecto/58 HTTP/1.1
Content-Type:  application/json

////////////////////////////
//  ACTA de CONSTITUCION  //
////////////////////////////

###LISTAR ACTA DE CONSTITUCION
GET http://localhost:8080/api/proyecto/ActaConstitucion/listarActaConstitucion/50 HTTP/1.1
Content-Type:  application/json

###MODIFICAR CAMPOS ACTA DE CONSTITUCION
PUT http://localhost:8080/api/proyecto/ActaConstitucion/modificarCampos HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 50,
  "nombreProyecto": "Hola123",
  "empresa": "Hola123",
  "cliente": "Hola123",
  "patrocinador": "Hola123",
  "gerente": "Hola123",
  "actaData": [
    {
      "idDetalle": 1,
      "idActaConstitucion": 11,
      "nombre": "Propósito y Justificación del Proyecto",
      "detalle": null,
      "activo": 1
    },
    {
      "idDetalle": 2,
      "idActaConstitucion": 11,
      "nombre": "Descripción del Proyecto y Entregables",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 3,
      "idActaConstitucion": 11,
      "nombre": "Presupuesto Estimado",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 4,
      "idActaConstitucion": 11,
      "nombre": "Premisas y Restricciones",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 5,
      "idActaConstitucion": 11,
      "nombre": "Riesgos Iniciales de Alto Nivel",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 6,
      "idActaConstitucion": 11,
      "nombre": "Requisitos de Aprobación del Proyecto",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 7,
      "idActaConstitucion": 11,
      "nombre": "Requerimientos de Alto Nivel",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 8,
      "idActaConstitucion": 11,
      "nombre": "Requerimientos del Producto",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 9,
      "idActaConstitucion": 11,
      "nombre": "Requerimientos del Proyecto",
      "detalle": "Probando123",
      "activo": 1
    },
    {
      "idDetalle": 10,
      "idActaConstitucion": 11,
      "nombre": "Elaborado pro",
      "detalle": "Probando123",
      "activo": 1
    }
  ]
}
###CREAR CAMPO AC
POST http://localhost:8080/api/proyecto/ActaConstitucion/crearCampos HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 50,
  "nombreCampo": "Prueba",
  "detalleCampo": "Prueba"
}
###LISTAR INTERESADOS AC
GET http://localhost:8080/api/proyecto/ActaConstitucion/listarInteresados/50 HTTP/1.1
Content-Type:  application/json

###INSERTAR INTERESADOS AC
POST http://localhost:8080/api/proyecto/ActaConstitucion/insertarInteresado HTTP/1.1
Content-Type:  application/json

{
  "idProyecto": 50, 
  "nombre": "Hola123", 
  "cargo": "Hola123",  
  "organizacion": "Hola123"
}
###ELIMINAR CAMPO AC
DELETE http://localhost:8080/api/proyecto/ActaConstitucion/eliminarCampo HTTP/1.1
Content-Type:  application/json

{
  "idDetalle": 64
}