POST http://localhost:3000/api/proyecto/insertarProyecto HTTP/1.1
Content-Type:  application/json

{
    "idUsuario": 77,
    "nombre": "Proyecto de darle mantenimiento a PUCP movil",
    "maxCantParticipantes": 8,
    "fechaInicio": null,
    "fechaFin": null
}

###

POST http://localhost:3000/api/proyecto/backlog/hu/eliminarHistoria HTTP/1.1
Content-Type:  application/json

{
    "idHistoriaDeUsuario" : 1
}